# DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.


from .add_ons_service import Add_onsService
from .carts_service import CartsService
from .categories_service import CategoriesService
from .checkout_settings_service import Checkout_settingsService
from .clients_service import ClientsService
from .configuration_service import ConfigurationService
from .google_shopping_service import Google_shoppingService
from .legal_content_service import Legal_contentService
from .oauth_service import OauthService
from .official_apps_service import Official_appsService
from .orders_service import OrdersService
from .payment_methods_service import Payment_methodsService
from .payment_signup_service import Payment_signupService
from .payments_service import PaymentsService
from .private_apps_service import Private_appsService
from .product_attribute_definitions_service import Product_attribute_definitionsService
from .product_settings_service import Product_settingsService
from .product_view_service import Product_viewService
from .products_service import ProductsService
from .scopes_service import ScopesService
from .shipping_zones_service import Shipping_zonesService
from .shop_service import ShopService
from .shop_id_service import Shop_idService
from .shops_service import ShopsService
from .signers_service import SignersService
from .users_service import UsersService
from .webhook_subscriptions_service import Webhook_subscriptionsService

from .http_client import HTTPClient


class Client:
    def __init__(self, base_uri="https://api-shop.beyondshop.cloud/api"):
        http_client = HTTPClient(base_uri)
        self.add_ons = Add_onsService(http_client)
        self.carts = CartsService(http_client)
        self.categories = CategoriesService(http_client)
        self.checkout_settings = Checkout_settingsService(http_client)
        self.clients = ClientsService(http_client)
        self.configuration = ConfigurationService(http_client)
        self.google_shopping = Google_shoppingService(http_client)
        self.legal_content = Legal_contentService(http_client)
        self.oauth = OauthService(http_client)
        self.official_apps = Official_appsService(http_client)
        self.orders = OrdersService(http_client)
        self.payment_methods = Payment_methodsService(http_client)
        self.payment_signup = Payment_signupService(http_client)
        self.payments = PaymentsService(http_client)
        self.private_apps = Private_appsService(http_client)
        self.product_attribute_definitions = Product_attribute_definitionsService(http_client)
        self.product_settings = Product_settingsService(http_client)
        self.product_view = Product_viewService(http_client)
        self.products = ProductsService(http_client)
        self.scopes = ScopesService(http_client)
        self.shipping_zones = Shipping_zonesService(http_client)
        self.shop = ShopService(http_client)
        self.shop_id = Shop_idService(http_client)
        self.shops = ShopsService(http_client)
        self.signers = SignersService(http_client)
        self.users = UsersService(http_client)
        self.webhook_subscriptions = Webhook_subscriptionsService(http_client)
        self.close = http_client.close
