# DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.


class Checkout_settingsService:
    def __init__(self, client):
        self.client = client

    def checkout_settings_get(self, headers=None, query_params=None, content_type="application/json"):
        """
        It is method for GET /checkout-settings
        """
        if query_params is None:
            query_params = {}

        uri = self.client.base_url + "/checkout-settings"
        return self.client.get(uri, None, headers, query_params, content_type)

    def checkout_settings_put(self, data, headers=None, query_params=None, content_type="application/json"):
        """
        It is method for PUT /checkout-settings
        """
        if query_params is None:
            query_params = {}

        uri = self.client.base_url + "/checkout-settings"
        return self.client.put(uri, data, headers, query_params, content_type)
