# DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.


class ConfigurationService:
    def __init__(self, client):
        self.client = client

    def configuration_invoice_number_get(self, headers=None, query_params=None, content_type="application/json"):
        """
        It is method for GET /configuration/invoice-number
        """
        if query_params is None:
            query_params = {}

        uri = self.client.base_url + "/configuration/invoice-number"
        return self.client.get(uri, None, headers, query_params, content_type)

    def configuration_invoice_number_patch(
            self,
            data,
            headers=None,
            query_params=None,
            content_type="application/json"):
        """
        It is method for PATCH /configuration/invoice-number
        """
        if query_params is None:
            query_params = {}

        uri = self.client.base_url + "/configuration/invoice-number"
        return self.client.patch(uri, data, headers, query_params, content_type)

    def configuration_invoice_number_put(self, data, headers=None, query_params=None, content_type="application/json"):
        """
        It is method for PUT /configuration/invoice-number
        """
        if query_params is None:
            query_params = {}

        uri = self.client.base_url + "/configuration/invoice-number"
        return self.client.put(uri, data, headers, query_params, content_type)

    def configuration_order_number_get(self, headers=None, query_params=None, content_type="application/json"):
        """
        It is method for GET /configuration/order-number
        """
        if query_params is None:
            query_params = {}

        uri = self.client.base_url + "/configuration/order-number"
        return self.client.get(uri, None, headers, query_params, content_type)

    def configuration_order_number_patch(self, data, headers=None, query_params=None, content_type="application/json"):
        """
        It is method for PATCH /configuration/order-number
        """
        if query_params is None:
            query_params = {}

        uri = self.client.base_url + "/configuration/order-number"
        return self.client.patch(uri, data, headers, query_params, content_type)

    def configuration_order_number_put(self, data, headers=None, query_params=None, content_type="application/json"):
        """
        It is method for PUT /configuration/order-number
        """
        if query_params is None:
            query_params = {}

        uri = self.client.base_url + "/configuration/order-number"
        return self.client.put(uri, data, headers, query_params, content_type)
