# DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.


class Legal_contentService:
    def __init__(self, client):
        self.client = client

    def legal_content_byName_get(self, name, headers=None, query_params=None, content_type="application/json"):
        """
        It is method for GET /legal-content/{name}
        """
        if query_params is None:
            query_params = {}

        uri = self.client.base_url + "/legal-content/" + name
        return self.client.get(uri, None, headers, query_params, content_type)

    def legal_content_byName_put(self, data, name, headers=None, query_params=None, content_type="application/json"):
        """
        It is method for PUT /legal-content/{name}
        """
        if query_params is None:
            query_params = {}

        uri = self.client.base_url + "/legal-content/" + name
        return self.client.put(uri, data, headers, query_params, content_type)

    def legal_content_get(self, headers=None, query_params=None, content_type="application/json"):
        """
        It is method for GET /legal-content
        """
        if query_params is None:
            query_params = {}

        uri = self.client.base_url + "/legal-content"
        return self.client.get(uri, None, headers, query_params, content_type)
