# DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.


class OauthService:
    def __init__(self, client):
        self.client = client

    def oauth_token_post(
            self,
            data,
            code,
            grant_type,
            headers=None,
            query_params=None,
            content_type="application/json"):
        """
        It is method for POST /oauth/token
        """
        if query_params is None:
            query_params = {}

        query_params['code'] = code
        query_params['grant_type'] = grant_type

        uri = self.client.base_url + "/oauth/token"
        return self.client.post(uri, data, headers, query_params, content_type)
