# DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.


class Official_appsService:
    def __init__(self, client):
        self.client = client

    def official_apps_byIdinstall_post(
            self,
            data,
            id,
            headers=None,
            query_params=None,
            content_type="application/json"):
        """
        It is method for POST /official-apps/{id}/install
        """
        if query_params is None:
            query_params = {}

        uri = self.client.base_url + "/official-apps/" + id + "/install"
        return self.client.post(uri, data, headers, query_params, content_type)
