# DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.


class Payment_signupService:
    def __init__(self, client):
        self.client = client

    def payment_signup_merchant_accountspaymentIntegration_delete(
            self, paymentIntegration, headers=None, query_params=None, content_type="application/json"):
        """
        It is method for DELETE /payment-signup/merchant-accounts/{paymentIntegration}
        """
        if query_params is None:
            query_params = {}

        uri = self.client.base_url + "/payment-signup/merchant-accounts/" + paymentIntegration
        return self.client.delete(uri, None, headers, query_params, content_type)

    def payment_signup_merchant_accountspaymentIntegration_get(
            self,
            paymentIntegration,
            headers=None,
            query_params=None,
            content_type="application/json"):
        """
        It is method for GET /payment-signup/merchant-accounts/{paymentIntegration}
        """
        if query_params is None:
            query_params = {}

        uri = self.client.base_url + "/payment-signup/merchant-accounts/" + paymentIntegration
        return self.client.get(uri, None, headers, query_params, content_type)

    def payment_signup_referralspaymentIntegration_post(
            self,
            data,
            paymentIntegration,
            headers=None,
            query_params=None,
            content_type="application/json"):
        """
        It is method for POST /payment-signup/referrals/{paymentIntegration}
        """
        if query_params is None:
            query_params = {}

        uri = self.client.base_url + "/payment-signup/referrals/" + paymentIntegration
        return self.client.post(uri, data, headers, query_params, content_type)
