# DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.


class Payment_methodsService:
    def __init__(self, client):
        self.client = client

    def payment_methods_byPaymentMethodIdactivate_post(
            self,
            data,
            paymentMethodId,
            headers=None,
            query_params=None,
            content_type="application/json"):
        """
        It is method for POST /payment-methods/{paymentMethodId}/activate
        """
        if query_params is None:
            query_params = {}

        uri = self.client.base_url + "/payment-methods/" + paymentMethodId + "/activate"
        return self.client.post(uri, data, headers, query_params, content_type)

    def payment_methods_byPaymentMethodIddeactivate_post(
            self,
            data,
            paymentMethodId,
            headers=None,
            query_params=None,
            content_type="application/json"):
        """
        It is method for POST /payment-methods/{paymentMethodId}/deactivate
        """
        if query_params is None:
            query_params = {}

        uri = self.client.base_url + "/payment-methods/" + paymentMethodId + "/deactivate"
        return self.client.post(uri, data, headers, query_params, content_type)

    def payment_methods_byPaymentMethodId_delete(
            self,
            paymentMethodId,
            headers=None,
            query_params=None,
            content_type="application/json"):
        """
        It is method for DELETE /payment-methods/{paymentMethodId}
        """
        if query_params is None:
            query_params = {}

        uri = self.client.base_url + "/payment-methods/" + paymentMethodId
        return self.client.delete(uri, None, headers, query_params, content_type)

    def payment_methods_byPaymentMethodId_get(
            self,
            paymentMethodId,
            headers=None,
            query_params=None,
            content_type="application/json"):
        """
        It is method for GET /payment-methods/{paymentMethodId}
        """
        if query_params is None:
            query_params = {}

        uri = self.client.base_url + "/payment-methods/" + paymentMethodId
        return self.client.get(uri, None, headers, query_params, content_type)

    def payment_methods_byPaymentMethodId_put(
            self,
            data,
            paymentMethodId,
            headers=None,
            query_params=None,
            content_type="application/json"):
        """
        It is method for PUT /payment-methods/{paymentMethodId}
        """
        if query_params is None:
            query_params = {}

        uri = self.client.base_url + "/payment-methods/" + paymentMethodId
        return self.client.put(uri, data, headers, query_params, content_type)

    def payment_methods_get(self, headers=None, query_params=None, content_type="application/json"):
        """
        It is method for GET /payment-methods
        """
        if query_params is None:
            query_params = {}

        uri = self.client.base_url + "/payment-methods"
        return self.client.get(uri, None, headers, query_params, content_type)

    def payment_methods_post(self, data, headers=None, query_params=None, content_type="application/json"):
        """
        It is method for POST /payment-methods
        """
        if query_params is None:
            query_params = {}

        uri = self.client.base_url + "/payment-methods"
        return self.client.post(uri, data, headers, query_params, content_type)

    def payment_methods_put(self, data, headers=None, query_params=None, content_type="application/json"):
        """
        It is method for PUT /payment-methods
        """
        if query_params is None:
            query_params = {}

        uri = self.client.base_url + "/payment-methods"
        return self.client.put(uri, data, headers, query_params, content_type)
