# DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.


class Product_attribute_definitionsService:
    def __init__(self, client):
        self.client = client

    def product_attribute_definitions_searchfind_by_namespace_and_name_get(
            self, name, namespace, headers=None, query_params=None, content_type="application/json"):
        """
        It is method for GET /product-attribute-definitions/search/find-by-namespace-and-name
        """
        if query_params is None:
            query_params = {}

        query_params['name'] = name
        query_params['namespace'] = namespace

        uri = self.client.base_url + "/product-attribute-definitions/search/find-by-namespace-and-name"
        return self.client.get(uri, None, headers, query_params, content_type)

    def product_attribute_definitions_searchfind_by_namespace_and_query_get(
            self, namespace, query, headers=None, query_params=None, content_type="application/json"):
        """
        It is method for GET /product-attribute-definitions/search/find-by-namespace-and-query
        """
        if query_params is None:
            query_params = {}

        query_params['namespace'] = namespace
        query_params['query'] = query

        uri = self.client.base_url + "/product-attribute-definitions/search/find-by-namespace-and-query"
        return self.client.get(uri, None, headers, query_params, content_type)

    def product_attribute_definitions_search_get(
            self,
            headers=None,
            query_params=None,
            content_type="application/json"):
        """
        It is method for GET /product-attribute-definitions/search
        """
        if query_params is None:
            query_params = {}

        uri = self.client.base_url + "/product-attribute-definitions/search"
        return self.client.get(uri, None, headers, query_params, content_type)

    def product_attribute_definitions_byId_delete(
            self,
            id,
            headers=None,
            query_params=None,
            content_type="application/json"):
        """
        It is method for DELETE /product-attribute-definitions/{id}
        """
        if query_params is None:
            query_params = {}

        uri = self.client.base_url + "/product-attribute-definitions/" + id
        return self.client.delete(uri, None, headers, query_params, content_type)

    def product_attribute_definitions_byId_get(
            self,
            id,
            locale,
            headers=None,
            query_params=None,
            content_type="application/json"):
        """
        It is method for GET /product-attribute-definitions/{id}
        """
        if query_params is None:
            query_params = {}

        query_params['locale'] = locale

        uri = self.client.base_url + "/product-attribute-definitions/" + id
        return self.client.get(uri, None, headers, query_params, content_type)

    def product_attribute_definitions_byId_patch(
            self,
            data,
            id,
            locale,
            headers=None,
            query_params=None,
            content_type="application/json"):
        """
        It is method for PATCH /product-attribute-definitions/{id}
        """
        if query_params is None:
            query_params = {}

        query_params['locale'] = locale

        uri = self.client.base_url + "/product-attribute-definitions/" + id
        return self.client.patch(uri, data, headers, query_params, content_type)

    def product_attribute_definitions_get(
            self,
            locale,
            headers=None,
            query_params=None,
            content_type="application/json"):
        """
        It is method for GET /product-attribute-definitions
        """
        if query_params is None:
            query_params = {}

        query_params['locale'] = locale

        uri = self.client.base_url + "/product-attribute-definitions"
        return self.client.get(uri, None, headers, query_params, content_type)

    def product_attribute_definitions_post(
            self,
            data,
            locale,
            headers=None,
            query_params=None,
            content_type="application/json"):
        """
        It is method for POST /product-attribute-definitions
        """
        if query_params is None:
            query_params = {}

        query_params['locale'] = locale

        uri = self.client.base_url + "/product-attribute-definitions"
        return self.client.post(uri, data, headers, query_params, content_type)
