# DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.


class ScopesService:
    def __init__(self, client):
        self.client = client

    def scopes_get(self, headers=None, query_params=None, content_type="application/json"):
        """
        It is method for GET /scopes
        """
        if query_params is None:
            query_params = {}

        uri = self.client.base_url + "/scopes"
        return self.client.get(uri, None, headers, query_params, content_type)
