# DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.


class Shipping_zonesService:
    def __init__(self, client):
        self.client = client

    def shipping_zones_searchfind_all_serviceable_countries_get(
            self, headers=None, query_params=None, content_type="application/json"):
        """
        It is method for GET /shipping-zones/search/find-all-serviceable-countries
        """
        if query_params is None:
            query_params = {}

        uri = self.client.base_url + "/shipping-zones/search/find-all-serviceable-countries"
        return self.client.get(uri, None, headers, query_params, content_type)

    def shipping_zones_byShippingZoneIdshipping_methodsshippingMethodId_delete(
            self, shippingZoneId, shippingMethodId, headers=None, query_params=None, content_type="application/json"):
        """
        It is method for DELETE /shipping-zones/{shippingZoneId}/shipping-methods/{shippingMethodId}
        """
        if query_params is None:
            query_params = {}

        uri = self.client.base_url + "/shipping-zones/" + shippingZoneId + "/shipping-methods/" + shippingMethodId
        return self.client.delete(uri, None, headers, query_params, content_type)

    def shipping_zones_byShippingZoneIdshipping_methodsshippingMethodId_get(
            self, shippingZoneId, shippingMethodId, headers=None, query_params=None, content_type="application/json"):
        """
        It is method for GET /shipping-zones/{shippingZoneId}/shipping-methods/{shippingMethodId}
        """
        if query_params is None:
            query_params = {}

        uri = self.client.base_url + "/shipping-zones/" + shippingZoneId + "/shipping-methods/" + shippingMethodId
        return self.client.get(uri, None, headers, query_params, content_type)

    def shipping_zones_byShippingZoneIdshipping_methodsshippingMethodId_put(
            self,
            data,
            shippingZoneId,
            shippingMethodId,
            headers=None,
            query_params=None,
            content_type="application/json"):
        """
        It is method for PUT /shipping-zones/{shippingZoneId}/shipping-methods/{shippingMethodId}
        """
        if query_params is None:
            query_params = {}

        uri = self.client.base_url + "/shipping-zones/" + shippingZoneId + "/shipping-methods/" + shippingMethodId
        return self.client.put(uri, data, headers, query_params, content_type)

    def shipping_zones_byShippingZoneIdshipping_methods_get(
            self,
            shippingZoneId,
            headers=None,
            query_params=None,
            content_type="application/json"):
        """
        It is method for GET /shipping-zones/{shippingZoneId}/shipping-methods
        """
        if query_params is None:
            query_params = {}

        uri = self.client.base_url + "/shipping-zones/" + shippingZoneId + "/shipping-methods"
        return self.client.get(uri, None, headers, query_params, content_type)

    def shipping_zones_byShippingZoneIdshipping_methods_post(
            self,
            data,
            shippingZoneId,
            headers=None,
            query_params=None,
            content_type="application/json"):
        """
        It is method for POST /shipping-zones/{shippingZoneId}/shipping-methods
        """
        if query_params is None:
            query_params = {}

        uri = self.client.base_url + "/shipping-zones/" + shippingZoneId + "/shipping-methods"
        return self.client.post(uri, data, headers, query_params, content_type)

    def shipping_zones_byShippingZoneId_delete(
            self,
            shippingZoneId,
            headers=None,
            query_params=None,
            content_type="application/json"):
        """
        It is method for DELETE /shipping-zones/{shippingZoneId}
        """
        if query_params is None:
            query_params = {}

        uri = self.client.base_url + "/shipping-zones/" + shippingZoneId
        return self.client.delete(uri, None, headers, query_params, content_type)

    def shipping_zones_byShippingZoneId_get(
            self,
            shippingZoneId,
            headers=None,
            query_params=None,
            content_type="application/json"):
        """
        It is method for GET /shipping-zones/{shippingZoneId}
        """
        if query_params is None:
            query_params = {}

        uri = self.client.base_url + "/shipping-zones/" + shippingZoneId
        return self.client.get(uri, None, headers, query_params, content_type)

    def shipping_zones_byShippingZoneId_put(
            self,
            data,
            shippingZoneId,
            headers=None,
            query_params=None,
            content_type="application/json"):
        """
        It is method for PUT /shipping-zones/{shippingZoneId}
        """
        if query_params is None:
            query_params = {}

        uri = self.client.base_url + "/shipping-zones/" + shippingZoneId
        return self.client.put(uri, data, headers, query_params, content_type)

    def shipping_zones_get(self, headers=None, query_params=None, content_type="application/json"):
        """
        It is method for GET /shipping-zones
        """
        if query_params is None:
            query_params = {}

        uri = self.client.base_url + "/shipping-zones"
        return self.client.get(uri, None, headers, query_params, content_type)

    def shipping_zones_post(self, data, headers=None, query_params=None, content_type="application/json"):
        """
        It is method for POST /shipping-zones
        """
        if query_params is None:
            query_params = {}

        uri = self.client.base_url + "/shipping-zones"
        return self.client.post(uri, data, headers, query_params, content_type)

    def shipping_zones_put(self, data, headers=None, query_params=None, content_type="application/json"):
        """
        It is method for PUT /shipping-zones
        """
        if query_params is None:
            query_params = {}

        uri = self.client.base_url + "/shipping-zones"
        return self.client.put(uri, data, headers, query_params, content_type)
