# DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.


class Shop_idService:
    def __init__(self, client):
        self.client = client

    def shop_id_get(self, headers=None, query_params=None, content_type="application/json"):
        """
        It is method for GET /shop-id
        """
        if query_params is None:
            query_params = {}

        uri = self.client.base_url + "/shop-id"
        return self.client.get(uri, None, headers, query_params, content_type)
