# DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.


class ShopsService:
    def __init__(self, client):
        self.client = client

    def shops_e0cfd5ec_c0de_472e_87c4_23813ae4fb19attributessecond_unknown_attribute_name_delete(
            self, headers=None, query_params=None, content_type="application/json"):
        """
        It is method for DELETE /shops/e0cfd5ec-c0de-472e-87c4-23813ae4fb19/attributes/second-unknown-attribute-name
        """
        if query_params is None:
            query_params = {}

        uri = self.client.base_url + "/shops/e0cfd5ec-c0de-472e-87c4-23813ae4fb19/attributes/second-unknown-attribute-name"
        return self.client.delete(uri, None, headers, query_params, content_type)

    def shops_get(self, status_provisioningCompleted, headers=None, query_params=None, content_type="application/json"):
        """
        It is method for GET /shops
        """
        if query_params is None:
            query_params = {}

        query_params['status.provisioningCompleted'] = status_provisioningCompleted

        uri = self.client.base_url + "/shops"
        return self.client.get(uri, None, headers, query_params, content_type)
