# DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.


class SignersService:
    def __init__(self, client):
        self.client = client

    def signers_byId_delete(self, id, headers=None, query_params=None, content_type="application/json"):
        """
        It is method for DELETE /signers/{id}
        """
        if query_params is None:
            query_params = {}

        uri = self.client.base_url + "/signers/" + id
        return self.client.delete(uri, None, headers, query_params, content_type)

    def signers_get(self, headers=None, query_params=None, content_type="application/json"):
        """
        It is method for GET /signers
        """
        if query_params is None:
            query_params = {}

        uri = self.client.base_url + "/signers"
        return self.client.get(uri, None, headers, query_params, content_type)

    def signers_post(self, data, headers=None, query_params=None, content_type="application/json"):
        """
        It is method for POST /signers
        """
        if query_params is None:
            query_params = {}

        uri = self.client.base_url + "/signers"
        return self.client.post(uri, data, headers, query_params, content_type)
