# DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.


class Add_onsService:
    def __init__(self, client):
        self.client = client

    def add_ons_installedid_delete(self, id, headers=None, query_params=None, content_type="application/json"):
        """
        It is method for DELETE /add-ons/installed/{id}
        """
        if query_params is None:
            query_params = {}

        uri = self.client.base_url + "/add-ons/installed/" + id
        return self.client.delete(uri, None, headers, query_params, content_type)

    def add_ons_installed_get(self, headers=None, query_params=None, content_type="application/json"):
        """
        It is method for GET /add-ons/installed
        """
        if query_params is None:
            query_params = {}

        uri = self.client.base_url + "/add-ons/installed"
        return self.client.get(uri, None, headers, query_params, content_type)
