# DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.


class CategoriesService:
    def __init__(self, client):
        self.client = client

    def categories_byId_delete(self, id, headers=None, query_params=None, content_type="application/json"):
        """
        It is method for DELETE /categories/{id}
        """
        if query_params is None:
            query_params = {}

        uri = self.client.base_url + "/categories/" + id
        return self.client.delete(uri, None, headers, query_params, content_type)

    def categories_byId_get(self, id, headers=None, query_params=None, content_type="application/json"):
        """
        It is method for GET /categories/{id}
        """
        if query_params is None:
            query_params = {}

        uri = self.client.base_url + "/categories/" + id
        return self.client.get(uri, None, headers, query_params, content_type)

    def categories_byId_patch(self, data, id, headers=None, query_params=None, content_type="application/json"):
        """
        It is method for PATCH /categories/{id}
        """
        if query_params is None:
            query_params = {}

        uri = self.client.base_url + "/categories/" + id
        return self.client.patch(uri, data, headers, query_params, content_type)

    def categories_byId_put(self, data, id, headers=None, query_params=None, content_type="application/json"):
        """
        It is method for PUT /categories/{id}
        """
        if query_params is None:
            query_params = {}

        uri = self.client.base_url + "/categories/" + id
        return self.client.put(uri, data, headers, query_params, content_type)

    def categories_get(self, headers=None, query_params=None, content_type="application/json"):
        """
        It is method for GET /categories
        """
        if query_params is None:
            query_params = {}

        uri = self.client.base_url + "/categories"
        return self.client.get(uri, None, headers, query_params, content_type)

    def categories_post(self, data, headers=None, query_params=None, content_type="application/json"):
        """
        It is method for POST /categories
        """
        if query_params is None:
            query_params = {}

        uri = self.client.base_url + "/categories"
        return self.client.post(uri, data, headers, query_params, content_type)
