# DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.


class ClientsService:
    def __init__(self, client):
        self.client = client

    def clients_byClientIdregenerate_secret_post(
            self,
            data,
            clientId,
            headers=None,
            query_params=None,
            content_type="application/json"):
        """
        It is method for POST /clients/{clientId}/regenerate-secret
        """
        if query_params is None:
            query_params = {}

        uri = self.client.base_url + "/clients/" + clientId + "/regenerate-secret"
        return self.client.post(uri, data, headers, query_params, content_type)

    def clients_byClientId_get(self, clientId, headers=None, query_params=None, content_type="application/json"):
        """
        It is method for GET /clients/{clientId}
        """
        if query_params is None:
            query_params = {}

        uri = self.client.base_url + "/clients/" + clientId
        return self.client.get(uri, None, headers, query_params, content_type)

    def clients_byClientId_put(self, data, clientId, headers=None, query_params=None, content_type="application/json"):
        """
        It is method for PUT /clients/{clientId}
        """
        if query_params is None:
            query_params = {}

        uri = self.client.base_url + "/clients/" + clientId
        return self.client.put(uri, data, headers, query_params, content_type)

    def clients_post(self, data, headers=None, query_params=None, content_type="application/json"):
        """
        It is method for POST /clients
        """
        if query_params is None:
            query_params = {}

        uri = self.client.base_url + "/clients"
        return self.client.post(uri, data, headers, query_params, content_type)
