# DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.


class OrdersService:
    def __init__(self, client):
        self.client = client

    def orders_searchfind_by_cart_id_get(self, headers=None, query_params=None, content_type="application/json"):
        """
        It is method for GET /orders/search/find-by-cart-id
        """
        if query_params is None:
            query_params = {}

        uri = self.client.base_url + "/orders/search/find-by-cart-id"
        return self.client.get(uri, None, headers, query_params, content_type)

    def orders_byIdsend_invoice_post(self, data, id, headers=None, query_params=None, content_type="application/json"):
        """
        It is method for POST /orders/{id}/send-invoice
        """
        if query_params is None:
            query_params = {}

        uri = self.client.base_url + "/orders/" + id + "/send-invoice"
        return self.client.post(uri, data, headers, query_params, content_type)

    def orders_byOrder_idbilling_address_put(
            self,
            data,
            order_id,
            headers=None,
            query_params=None,
            content_type="application/json"):
        """
        It is method for PUT /orders/{order-id}/billing-address
        """
        if query_params is None:
            query_params = {}

        uri = self.client.base_url + "/orders/" + order_id + "/billing-address"
        return self.client.put(uri, data, headers, query_params, content_type)

    def orders_byOrder_idcancel_post(
            self,
            data,
            order_id,
            headers=None,
            query_params=None,
            content_type="application/json"):
        """
        It is method for POST /orders/{order-id}/cancel
        """
        if query_params is None:
            query_params = {}

        uri = self.client.base_url + "/orders/" + order_id + "/cancel"
        return self.client.post(uri, data, headers, query_params, content_type)

    def orders_byOrder_idcreate_invoice_post(
            self,
            data,
            order_id,
            headers=None,
            query_params=None,
            content_type="application/json"):
        """
        It is method for POST /orders/{order-id}/create-invoice
        """
        if query_params is None:
            query_params = {}

        uri = self.client.base_url + "/orders/" + order_id + "/create-invoice"
        return self.client.post(uri, data, headers, query_params, content_type)

    def orders_byOrder_idevents_get(self, order_id, headers=None, query_params=None, content_type="application/json"):
        """
        It is method for GET /orders/{order-id}/events
        """
        if query_params is None:
            query_params = {}

        uri = self.client.base_url + "/orders/" + order_id + "/events"
        return self.client.get(uri, None, headers, query_params, content_type)

    def orders_byOrder_idorder_note_put(
            self,
            data,
            order_id,
            headers=None,
            query_params=None,
            content_type="application/json"):
        """
        It is method for PUT /orders/{order-id}/order-note
        """
        if query_params is None:
            query_params = {}

        uri = self.client.base_url + "/orders/" + order_id + "/order-note"
        return self.client.put(uri, data, headers, query_params, content_type)

    def orders_byOrder_idprocessescancelationscancelation_process_id_get(
            self,
            order_id,
            cancelation_process_id,
            headers=None,
            query_params=None,
            content_type="application/json"):
        """
        It is method for GET /orders/{order-id}/processes/cancelations/{cancelation-process-id}
        """
        if query_params is None:
            query_params = {}

        uri = self.client.base_url + "/orders/" + order_id + "/processes/cancelations/" + cancelation_process_id
        return self.client.get(uri, None, headers, query_params, content_type)

    def orders_byOrder_idprocessescancelations_get(
            self,
            order_id,
            headers=None,
            query_params=None,
            content_type="application/json"):
        """
        It is method for GET /orders/{order-id}/processes/cancelations
        """
        if query_params is None:
            query_params = {}

        uri = self.client.base_url + "/orders/" + order_id + "/processes/cancelations"
        return self.client.get(uri, None, headers, query_params, content_type)

    def orders_byOrder_idprocessescancelations_post(
            self,
            data,
            order_id,
            headers=None,
            query_params=None,
            content_type="application/json"):
        """
        It is method for POST /orders/{order-id}/processes/cancelations
        """
        if query_params is None:
            query_params = {}

        uri = self.client.base_url + "/orders/" + order_id + "/processes/cancelations"
        return self.client.post(uri, data, headers, query_params, content_type)

    def orders_byOrder_idprocessespaymentsactive_get(
            self,
            order_id,
            headers=None,
            query_params=None,
            content_type="application/json"):
        """
        It is method for GET /orders/{order-id}/processes/payments/active
        """
        if query_params is None:
            query_params = {}

        uri = self.client.base_url + "/orders/" + order_id + "/processes/payments/active"
        return self.client.get(uri, None, headers, query_params, content_type)

    def orders_byOrder_idprocessespaymentspayment_process_idmark_paid_post(
            self, data, order_id, payment_process_id, headers=None, query_params=None, content_type="application/json"):
        """
        It is method for POST /orders/{order-id}/processes/payments/{payment-process-id}/mark-paid
        """
        if query_params is None:
            query_params = {}

        uri = self.client.base_url + "/orders/" + order_id + "/processes/payments/" + payment_process_id + "/mark-paid"
        return self.client.post(uri, data, headers, query_params, content_type)

    def orders_byOrder_idprocessespaymentspayment_process_idmark_voided_post(
            self, data, order_id, payment_process_id, headers=None, query_params=None, content_type="application/json"):
        """
        It is method for POST /orders/{order-id}/processes/payments/{payment-process-id}/mark-voided
        """
        if query_params is None:
            query_params = {}

        uri = self.client.base_url + "/orders/" + order_id + "/processes/payments/" + payment_process_id + "/mark-voided"
        return self.client.post(uri, data, headers, query_params, content_type)

    def orders_byOrder_idprocessespaymentspayment_process_id_get(
            self,
            order_id,
            payment_process_id,
            headers=None,
            query_params=None,
            content_type="application/json"):
        """
        It is method for GET /orders/{order-id}/processes/payments/{payment-process-id}
        """
        if query_params is None:
            query_params = {}

        uri = self.client.base_url + "/orders/" + order_id + "/processes/payments/" + payment_process_id
        return self.client.get(uri, None, headers, query_params, content_type)

    def orders_byOrder_idprocessespayments_get(
            self,
            order_id,
            headers=None,
            query_params=None,
            content_type="application/json"):
        """
        It is method for GET /orders/{order-id}/processes/payments
        """
        if query_params is None:
            query_params = {}

        uri = self.client.base_url + "/orders/" + order_id + "/processes/payments"
        return self.client.get(uri, None, headers, query_params, content_type)

    def orders_byOrder_idprocessespayments_post(
            self,
            data,
            order_id,
            headers=None,
            query_params=None,
            content_type="application/json"):
        """
        It is method for POST /orders/{order-id}/processes/payments
        """
        if query_params is None:
            query_params = {}

        uri = self.client.base_url + "/orders/" + order_id + "/processes/payments"
        return self.client.post(uri, data, headers, query_params, content_type)

    def orders_byOrder_idprocessesrefundsactivemark_paid_post(
            self, data, order_id, headers=None, query_params=None, content_type="application/json"):
        """
        It is method for POST /orders/{order-id}/processes/refunds/active/mark-paid
        """
        if query_params is None:
            query_params = {}

        uri = self.client.base_url + "/orders/" + order_id + "/processes/refunds/active/mark-paid"
        return self.client.post(uri, data, headers, query_params, content_type)

    def orders_byOrder_idprocessesrefundsactive_get(
            self,
            order_id,
            headers=None,
            query_params=None,
            content_type="application/json"):
        """
        It is method for GET /orders/{order-id}/processes/refunds/active
        """
        if query_params is None:
            query_params = {}

        uri = self.client.base_url + "/orders/" + order_id + "/processes/refunds/active"
        return self.client.get(uri, None, headers, query_params, content_type)

    def orders_byOrder_idprocessesrefundsid_get(
            self,
            order_id,
            id,
            headers=None,
            query_params=None,
            content_type="application/json"):
        """
        It is method for GET /orders/{order-id}/processes/refunds/{id}
        """
        if query_params is None:
            query_params = {}

        uri = self.client.base_url + "/orders/" + order_id + "/processes/refunds/" + id
        return self.client.get(uri, None, headers, query_params, content_type)

    def orders_byOrder_idprocessesrefunds_get(
            self,
            order_id,
            headers=None,
            query_params=None,
            content_type="application/json"):
        """
        It is method for GET /orders/{order-id}/processes/refunds
        """
        if query_params is None:
            query_params = {}

        uri = self.client.base_url + "/orders/" + order_id + "/processes/refunds"
        return self.client.get(uri, None, headers, query_params, content_type)

    def orders_byOrder_idprocessesreturnsreturn_process_id_get(
            self,
            order_id,
            return_process_id,
            headers=None,
            query_params=None,
            content_type="application/json"):
        """
        It is method for GET /orders/{order-id}/processes/returns/{return-process-id}
        """
        if query_params is None:
            query_params = {}

        uri = self.client.base_url + "/orders/" + order_id + "/processes/returns/" + return_process_id
        return self.client.get(uri, None, headers, query_params, content_type)

    def orders_byOrder_idprocessesreturns_get(
            self,
            order_id,
            headers=None,
            query_params=None,
            content_type="application/json"):
        """
        It is method for GET /orders/{order-id}/processes/returns
        """
        if query_params is None:
            query_params = {}

        uri = self.client.base_url + "/orders/" + order_id + "/processes/returns"
        return self.client.get(uri, None, headers, query_params, content_type)

    def orders_byOrder_idprocessesreturns_post(
            self,
            data,
            order_id,
            headers=None,
            query_params=None,
            content_type="application/json"):
        """
        It is method for POST /orders/{order-id}/processes/returns
        """
        if query_params is None:
            query_params = {}

        uri = self.client.base_url + "/orders/" + order_id + "/processes/returns"
        return self.client.post(uri, data, headers, query_params, content_type)

    def orders_byOrder_idprocessesshippingsshipping_process_idmark_delivered_post(
            self, data, order_id, shipping_process_id, headers=None, query_params=None, content_type="application/json"):
        """
        It is method for POST /orders/{order-id}/processes/shippings/{shipping-process-id}/mark-delivered
        """
        if query_params is None:
            query_params = {}

        uri = self.client.base_url + "/orders/" + order_id + "/processes/shippings/" + shipping_process_id + "/mark-delivered"
        return self.client.post(uri, data, headers, query_params, content_type)

    def orders_byOrder_idprocessesshippingsshipping_process_idmark_shipped_post(
            self, data, order_id, shipping_process_id, headers=None, query_params=None, content_type="application/json"):
        """
        It is method for POST /orders/{order-id}/processes/shippings/{shipping-process-id}/mark-shipped
        """
        if query_params is None:
            query_params = {}

        uri = self.client.base_url + "/orders/" + order_id + "/processes/shippings/" + shipping_process_id + "/mark-shipped"
        return self.client.post(uri, data, headers, query_params, content_type)

    def orders_byOrder_idprocessesshippingsshipping_process_id_get(
            self,
            order_id,
            shipping_process_id,
            headers=None,
            query_params=None,
            content_type="application/json"):
        """
        It is method for GET /orders/{order-id}/processes/shippings/{shipping-process-id}
        """
        if query_params is None:
            query_params = {}

        uri = self.client.base_url + "/orders/" + order_id + "/processes/shippings/" + shipping_process_id
        return self.client.get(uri, None, headers, query_params, content_type)

    def orders_byOrder_idprocessesshippings_get(
            self,
            order_id,
            headers=None,
            query_params=None,
            content_type="application/json"):
        """
        It is method for GET /orders/{order-id}/processes/shippings
        """
        if query_params is None:
            query_params = {}

        uri = self.client.base_url + "/orders/" + order_id + "/processes/shippings"
        return self.client.get(uri, None, headers, query_params, content_type)

    def orders_byOrder_idprocessesshippings_post(
            self,
            data,
            order_id,
            headers=None,
            query_params=None,
            content_type="application/json"):
        """
        It is method for POST /orders/{order-id}/processes/shippings
        """
        if query_params is None:
            query_params = {}

        uri = self.client.base_url + "/orders/" + order_id + "/processes/shippings"
        return self.client.post(uri, data, headers, query_params, content_type)

    def orders_byOrder_idprocesses_get(
            self,
            order_id,
            headers=None,
            query_params=None,
            content_type="application/json"):
        """
        It is method for GET /orders/{order-id}/processes
        """
        if query_params is None:
            query_params = {}

        uri = self.client.base_url + "/orders/" + order_id + "/processes"
        return self.client.get(uri, None, headers, query_params, content_type)

    def orders_byOrder_idshipping_address_put(
            self,
            data,
            order_id,
            headers=None,
            query_params=None,
            content_type="application/json"):
        """
        It is method for PUT /orders/{order-id}/shipping-address
        """
        if query_params is None:
            query_params = {}

        uri = self.client.base_url + "/orders/" + order_id + "/shipping-address"
        return self.client.put(uri, data, headers, query_params, content_type)

    def orders_byOrder_id_get(self, order_id, headers=None, query_params=None, content_type="application/json"):
        """
        It is method for GET /orders/{order-id}
        """
        if query_params is None:
            query_params = {}

        uri = self.client.base_url + "/orders/" + order_id
        return self.client.get(uri, None, headers, query_params, content_type)

    def orders_get(self, headers=None, query_params=None, content_type="application/json"):
        """
        It is method for GET /orders
        """
        if query_params is None:
            query_params = {}

        uri = self.client.base_url + "/orders"
        return self.client.get(uri, None, headers, query_params, content_type)
