# DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.


class PaymentsService:
    def __init__(self, client):
        self.client = client

    def payments_byPaymentIdapprove_post(
            self,
            data,
            paymentId,
            headers=None,
            query_params=None,
            content_type="application/json"):
        """
        It is method for POST /payments/{paymentId}/approve
        """
        if query_params is None:
            query_params = {}

        uri = self.client.base_url + "/payments/" + paymentId + "/approve"
        return self.client.post(uri, data, headers, query_params, content_type)

    def payments_byPaymentIdcancel_post(
            self,
            data,
            paymentId,
            headers=None,
            query_params=None,
            content_type="application/json"):
        """
        It is method for POST /payments/{paymentId}/cancel
        """
        if query_params is None:
            query_params = {}

        uri = self.client.base_url + "/payments/" + paymentId + "/cancel"
        return self.client.post(uri, data, headers, query_params, content_type)

    def payments_byPaymentIdcapture_post(
            self,
            data,
            paymentId,
            headers=None,
            query_params=None,
            content_type="application/json"):
        """
        It is method for POST /payments/{paymentId}/capture
        """
        if query_params is None:
            query_params = {}

        uri = self.client.base_url + "/payments/" + paymentId + "/capture"
        return self.client.post(uri, data, headers, query_params, content_type)

    def payments_byPaymentIdrefund_post(
            self,
            data,
            paymentId,
            headers=None,
            query_params=None,
            content_type="application/json"):
        """
        It is method for POST /payments/{paymentId}/refund
        """
        if query_params is None:
            query_params = {}

        uri = self.client.base_url + "/payments/" + paymentId + "/refund"
        return self.client.post(uri, data, headers, query_params, content_type)

    def payments_byPaymentIdstatus_post(
            self,
            data,
            paymentId,
            headers=None,
            query_params=None,
            content_type="application/json"):
        """
        It is method for POST /payments/{paymentId}/status
        """
        if query_params is None:
            query_params = {}

        uri = self.client.base_url + "/payments/" + paymentId + "/status"
        return self.client.post(uri, data, headers, query_params, content_type)

    def payments_post(self, data, headers=None, query_params=None, content_type="application/json"):
        """
        It is method for POST /payments
        """
        if query_params is None:
            query_params = {}

        uri = self.client.base_url + "/payments"
        return self.client.post(uri, data, headers, query_params, content_type)
