# DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.


class Product_viewService:
    def __init__(self, client):
        self.client = client

    def product_view_categoriessearchfind_by_label_get(
            self,
            label,
            headers=None,
            query_params=None,
            content_type="application/json"):
        """
        It is method for GET /product-view/categories/search/find-by-label
        """
        if query_params is None:
            query_params = {}

        query_params['label'] = label

        uri = self.client.base_url + "/product-view/categories/search/find-by-label"
        return self.client.get(uri, None, headers, query_params, content_type)

    def product_view_categoriessearchfind_by_product_get(
            self,
            productId,
            headers=None,
            query_params=None,
            content_type="application/json"):
        """
        It is method for GET /product-view/categories/search/find-by-product
        """
        if query_params is None:
            query_params = {}

        query_params['productId'] = productId

        uri = self.client.base_url + "/product-view/categories/search/find-by-product"
        return self.client.get(uri, None, headers, query_params, content_type)

    def product_view_categoriescategoryIdproducts_get(
            self,
            categoryId,
            headers=None,
            query_params=None,
            content_type="application/json"):
        """
        It is method for GET /product-view/categories/{categoryId}/products
        """
        if query_params is None:
            query_params = {}

        uri = self.client.base_url + "/product-view/categories/" + categoryId + "/products"
        return self.client.get(uri, None, headers, query_params, content_type)

    def product_view_categoriescategoryId_get(
            self,
            categoryId,
            headers=None,
            query_params=None,
            content_type="application/json"):
        """
        It is method for GET /product-view/categories/{categoryId}
        """
        if query_params is None:
            query_params = {}

        uri = self.client.base_url + "/product-view/categories/" + categoryId
        return self.client.get(uri, None, headers, query_params, content_type)

    def product_view_categories_get(self, headers=None, query_params=None, content_type="application/json"):
        """
        It is method for GET /product-view/categories
        """
        if query_params is None:
            query_params = {}

        uri = self.client.base_url + "/product-view/categories"
        return self.client.get(uri, None, headers, query_params, content_type)

    def product_view_productssearchfind_available_tags_get(
            self, headers=None, query_params=None, content_type="application/json"):
        """
        It is method for GET /product-view/products/search/find-available-tags
        """
        if query_params is None:
            query_params = {}

        uri = self.client.base_url + "/product-view/products/search/find-available-tags"
        return self.client.get(uri, None, headers, query_params, content_type)

    def product_view_productssearchfind_by_category_get(
            self,
            categoryId,
            headers=None,
            query_params=None,
            content_type="application/json"):
        """
        It is method for GET /product-view/products/search/find-by-category
        """
        if query_params is None:
            query_params = {}

        query_params['categoryId'] = categoryId

        uri = self.client.base_url + "/product-view/products/search/find-by-category"
        return self.client.get(uri, None, headers, query_params, content_type)

    def product_view_productssearchfind_by_query_post(
            self,
            data,
            headers=None,
            query_params=None,
            content_type="application/json"):
        """
        It is method for POST /product-view/products/search/find-by-query
        """
        if query_params is None:
            query_params = {}

        uri = self.client.base_url + "/product-view/products/search/find-by-query"
        return self.client.post(uri, data, headers, query_params, content_type)

    def product_view_productssearchfind_by_search_term_get(
            self, query, headers=None, query_params=None, content_type="application/json"):
        """
        It is method for GET /product-view/products/search/find-by-search-term
        """
        if query_params is None:
            query_params = {}

        query_params['query'] = query

        uri = self.client.base_url + "/product-view/products/search/find-by-search-term"
        return self.client.get(uri, None, headers, query_params, content_type)

    def product_view_productssearchfind_by_tags_get(
            self,
            tag,
            headers=None,
            query_params=None,
            content_type="application/json"):
        """
        It is method for GET /product-view/products/search/find-by-tags
        """
        if query_params is None:
            query_params = {}

        query_params['tag'] = tag

        uri = self.client.base_url + "/product-view/products/search/find-by-tags"
        return self.client.get(uri, None, headers, query_params, content_type)

    def product_view_productsproductId_get(
            self,
            productId,
            headers=None,
            query_params=None,
            content_type="application/json"):
        """
        It is method for GET /product-view/products/{productId}
        """
        if query_params is None:
            query_params = {}

        uri = self.client.base_url + "/product-view/products/" + productId
        return self.client.get(uri, None, headers, query_params, content_type)

    def product_view_products_get(self, headers=None, query_params=None, content_type="application/json"):
        """
        It is method for GET /product-view/products
        """
        if query_params is None:
            query_params = {}

        uri = self.client.base_url + "/product-view/products"
        return self.client.get(uri, None, headers, query_params, content_type)
