# DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.


class Product_settingsService:
    def __init__(self, client):
        self.client = client

    def product_settings_get(self, headers=None, query_params=None, content_type="application/json"):
        """
        It is method for GET /product-settings
        """
        if query_params is None:
            query_params = {}

        uri = self.client.base_url + "/product-settings"
        return self.client.get(uri, None, headers, query_params, content_type)

    def product_settings_patch(self, data, headers=None, query_params=None, content_type="application/json"):
        """
        It is method for PATCH /product-settings
        """
        if query_params is None:
            query_params = {}

        uri = self.client.base_url + "/product-settings"
        return self.client.patch(uri, data, headers, query_params, content_type)
