# DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.


class Webhook_subscriptionsService:
    def __init__(self, client):
        self.client = client

    def webhook_subscriptions_byIdactivate_post(
            self,
            data,
            id,
            headers=None,
            query_params=None,
            content_type="application/json"):
        """
        It is method for POST /webhook-subscriptions/{id}/activate
        """
        if query_params is None:
            query_params = {}

        uri = self.client.base_url + "/webhook-subscriptions/" + id + "/activate"
        return self.client.post(uri, data, headers, query_params, content_type)

    def webhook_subscriptions_byIddeactivate_post(
            self,
            data,
            id,
            headers=None,
            query_params=None,
            content_type="application/json"):
        """
        It is method for POST /webhook-subscriptions/{id}/deactivate
        """
        if query_params is None:
            query_params = {}

        uri = self.client.base_url + "/webhook-subscriptions/" + id + "/deactivate"
        return self.client.post(uri, data, headers, query_params, content_type)

    def webhook_subscriptions_byId_delete(self, id, headers=None, query_params=None, content_type="application/json"):
        """
        It is method for DELETE /webhook-subscriptions/{id}
        """
        if query_params is None:
            query_params = {}

        uri = self.client.base_url + "/webhook-subscriptions/" + id
        return self.client.delete(uri, None, headers, query_params, content_type)

    def webhook_subscriptions_byId_get(self, id, headers=None, query_params=None, content_type="application/json"):
        """
        It is method for GET /webhook-subscriptions/{id}
        """
        if query_params is None:
            query_params = {}

        uri = self.client.base_url + "/webhook-subscriptions/" + id
        return self.client.get(uri, None, headers, query_params, content_type)

    def webhook_subscriptions_byId_put(
            self,
            data,
            id,
            headers=None,
            query_params=None,
            content_type="application/json"):
        """
        It is method for PUT /webhook-subscriptions/{id}
        """
        if query_params is None:
            query_params = {}

        uri = self.client.base_url + "/webhook-subscriptions/" + id
        return self.client.put(uri, data, headers, query_params, content_type)

    def webhook_subscriptions_get(self, headers=None, query_params=None, content_type="application/json"):
        """
        It is method for GET /webhook-subscriptions
        """
        if query_params is None:
            query_params = {}

        uri = self.client.base_url + "/webhook-subscriptions"
        return self.client.get(uri, None, headers, query_params, content_type)

    def webhook_subscriptions_post(self, data, headers=None, query_params=None, content_type="application/json"):
        """
        It is method for POST /webhook-subscriptions
        """
        if query_params is None:
            query_params = {}

        uri = self.client.base_url + "/webhook-subscriptions"
        return self.client.post(uri, data, headers, query_params, content_type)
